spring:
  application:
    name: ms1
  profiles:
    active:
    - default
  security:
    user:
      name: testwithgit
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true