spring:
  application:
    name: ms3
  profiles:
    active:
    - default
  security:
    user:
      name: ms3NoGit
  cloud:
    config:
      uri: 
      - http://localhost:8888/
  datasource:
    url: jdbc:mysql://localhost/test
    username: root
    password: 
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate4.SpringSessionContext
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
