server:
  port: 9100
spring:
  application:
    name: authenticationservice
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      auto-offset-reset: earliest
      group-id: auth
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  profiles:
    active:
    - default
  cloud:
    config:
      uri:
      - http://localhost:8888/
  datasource:
    url: jdbc:h2:file:~/authdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    dbcp2:
      driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties: 
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true